### ISSUE TITLE
Issue in Exercise 5 Task 3

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-App-modernization#106]
[Exercise 5 Task 3 Step 10](https://github.com/microsoft/MCW-App-modernization/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-3-testing-serverless-order-processing): After filling the **shipping information and coupon code information (FREE)**, when I click on **Submit Order** order is not being placed and it opens the same **AddressAndPayment** page by erasing the coupon code value (Didn't receive any error message).

I have verified the connection string values that are added in the previous tasks and they are correct. 

Can this issue be addressed asap as we have workshops scheduled in this week??

**Comment by tejaswini972** [comment]
@timahenning any update on this??

**Comment by timahenning** [comment]
@tejaswini972 I am running through the lab today.
