### ISSUE TITLE
SQL Backup not found

### ISSUE THREAD

**Issue by NicoThiemer** [microsoft/MCW-App-modernization#110]
When I created the lab, the SQL server is created and the database too. But there is not content in the database. No tables, nothing. 
In the script configure-sqlvm.ps1 are in line 52: Attach the downloaded backup files.
But, how can I find this files? I can't find it in this repository.

**Comment by NicoThiemer** [comment]
Hm, there is no reaction?

**Comment by DawnmarieDesJardins** [comment]
@NicoThiemer - Thank you for reaching out, an author will review the issue as soon as possible. Please allow 5-10 business days for issue resolution as stated on the ReadMe page.

**Comment by timahenning** [comment]
Hi @NicoThiemer, what exercise and task are you on?

**Comment by timahenning** [comment]
Hi @NicoThiemer, I just ran the lab.  The tables and data were created.  Make sure you log in to the WebVM and let the PowerShell script finish as suggested in Exercise 2 step 7.

![image](https://user-images.githubusercontent.com/48766586/145717301-0da7a8c8-de74-4428-ab73-92207c6a4e7a.png)

**Comment by NicoThiemer** [comment]
OK, I'm MCT and this workshop is part of the Microsoft AZ-305 course. In this course, I start the lab, which is automatically(!) deployed by the training provider. I have no control over it. When the lab is finished, I will also have two VMs in Azure. But the database is not installed on the database VM. I would like to know, what code creates the database? To solve the problem, could you please provide a database backup asap? That would solve the problem. The course starts today…

**Comment by NicoThiemer** [comment]
> 

I did it. And in the script  configure-sqlvm.ps1, there is line 52: "Attach the downloaded backup files".

**Comment by timahenning** [comment]
Hi @NicoThiemer, the database is created and seeded when the web application starts for the first time. 

Take a look at the PartsUnlimitedWebsite project:
1. Program.cs -  context.Database.EnsureCreated();
2. SampleData.cs class.
 
Your provider may need to update their image of the lab.  Optionally, you could run the first part of the lab in a separate subscription and grab a database backup from there.

**Comment by NicoThiemer** [comment]
Ah, great. Thank you @timahenning. This step (start the web application) was missing in my manual.
