### ISSUE TITLE
GitHub Action getting failed in Exercise-4 Task-3

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-App-modernization#111]
In [Exercise-4 Task-3: Setting up CI/CD with GitHub Actions Step-14](https://github.com/microsoft/MCW-App-modernization/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-3-setting-up-cicd-with-github-actions), github action to update stagingdeploy.yml is getting failed with the following error in the screenshot.

![image](https://user-images.githubusercontent.com/83394010/145459284-f458cbb3-ea77-4186-b045-80f2138a58d9.png)

Tried by Authorizing the App service - Deployment Center by following https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel. But still it is failing. 

And the same thing happening with the Task 4: Pushing code changes to staging and production, at step-8 after pushing the changes from visual studio code and the New Home Page Title github action is also getting failed with the same error.

In [Exercise-5 Task-3 Step-9](https://github.com/microsoft/MCW-App-modernization/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-3-setting-up-cicd-with-github-actions), unable to process the order request. 

![image](https://user-images.githubusercontent.com/83394010/145478615-e6d21535-3bc9-4398-ad9a-425acb9670a6.png)

**Comment by eldridgeb** [comment]
We noticed this yesterday too. I suspect this may be related to this recent release to the GitHub Actions image which bumped up Node and Npm versions:
https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211129.1

Thought I'm not really sure what to do about that.. :/

**Comment by akn9050** [comment]
hi @timahenning @DawnmarieDesJardins I noticed in exercise 4 task 3 step 11, there is no file with following path C:\MCW\MCW-App-modernization-main\Hands-on lab\lab-files\workflow\stagingdeploy.yml, and 

we already have the file in workflow folder locally after pulling the changes from remote at this step which has different content as compared with screenshot instructions. 

Can we please investigate and priorities this issue.

**Comment by fatihdurgut** [comment]
My HOL also failed in the same place.  

PartsUnlimitedWebsite.csporj has the following script. GitHub could not run the npm install part. 

  <Target Name="PrecompileScript" BeforeTargets="BeforeBuild">
    <Exec Command="npm install --python=python2.7" />
    <Exec Command="npm config set python python2.7" />
    <Exec Command="npm install -g grunt-cli --force" />
    <Exec Command="grunt" />
  </Target>

**Comment by eldridgeb** [comment]
As a workaround, you can switch to the Windows GitHub hosted runner. The build completes without error and looks okay to me.

So change:
https://github.com/microsoft/MCW-App-modernization/blob/main/Hands-on%20lab/lab-files/workflow/stagingdeploy.yml#L15
to `windows-latest`

**Comment by fatihdurgut** [comment]
> windows-latest

This worked. Thanks.

**Comment by timahenning** [comment]
> C:\MCW\MCW-App-modernization-main\Hands-on lab\lab-files\workflow

Hi @

> hi @timahenning @DawnmarieDesJardins I noticed in exercise 4 task 3 step 11, there is no file with following path C:\MCW\MCW-App-modernization-main\Hands-on lab\lab-files\workflow\stagingdeploy.yml, and
> 
> we already have the file in workflow folder locally after pulling the changes from remote at this step which has different content as compared with screenshot instructions.
> 
> Can we please investigate and priorities this issue.

I have created a new issue for this separate thread.

**Comment by timahenning** [comment]
Hi @eldridgeb and @fatihdurgut,

Thank you for your initial investigation.  I guess the **ubuntu-latest** image has been updated.  I have tested with windows-2019.

Tim

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge or PR #114
