### ISSUE TITLE
Ex:4-Task3: GitHub Action doesn't deploy the content folder

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/MCW-App-modernization#112]
The GitHub Action doesn't deploy the content folder to the staging environment. 

![image](https://user-images.githubusercontent.com/4159116/145716286-31d69632-1eec-4243-ab35-16f030190517.png)

result 
![image](https://user-images.githubusercontent.com/4159116/145716297-90e25fd1-49ef-46bd-ba02-a5eea426a591.png)

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge or PR #114
