### ISSUE TITLE
Image is too busy

### ISSUE THREAD

**Issue by emilysaeli** [Microsoft/MCW-App-modernization#2]
Image is too busy to be read. There is too much text, not all of it reads left to right and text is too small to read without significantly enhancing image. Can't even really get in with the eyedropper to check color contrast but there are places it definitely won't pass. 

https://github.com/Microsoft/MCW-App-modernization/raw/master/WDS/images/Whiteboarddesignsessiontrainerguide-Appmodernizationimages/media/image3.png

**Comment by DawnmarieDesJardins** [comment]
Closing with discussion.
