### ISSUE TITLE
Move the reminder that a pre steps are required prior on doing the HOL?

### ISSUE THREAD

**Issue by ronnelsantiago** [Microsoft/MCW-App-modernization#23]
Should we be reminding people that this text: 
**You should follow all steps provided before attending the Hands-on lab** 
which is currently on `Before the HOL - App modernization.md` be in the main md file? i.e `HOL step-by-step - App modernization.md`?

**Comment by DawnmarieDesJardins** [comment]
Thanks Ronnel!
This workshop will be going through an update shortly so I've marked this issue as an enhancement to be reviewed then.

**Comment by ronnelsantiago** [comment]
Good to hear that.

**Comment by jstulo** [comment]
The standard for all of the MCWs is to place the reminder within Before the HOL. In keeping with that standard, I am closing this issue. I will mention the suggestion as an option for all of the MCWs.
