### ISSUE TITLE
Image does not pass color contrast

### ISSUE THREAD

**Issue by emilysaeli** [Microsoft/MCW-App-modernization#3]
Lighter blue and white do not pass color contrast test. See copied results below. 

https://github.com/Microsoft/MCW-App-modernization/raw/master/WDS/images/Whiteboarddesignsessiontrainerguide-Appmodernizationimages/media/image2.png

Foreground:#FFFFFF
Background:#5B9BD5

The contrast ratio is: just below 3.0:1

Text failed at Level AA
Text failed at Level AAA
Large text failed at Level AA
Large text failed at Level AAA

**Comment by DawnmarieDesJardins** [comment]
Colors resolved and replaced
