### ISSUE TITLE
Exercise 7: Task 4: Issue with downloading of Policy Document

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-App-modernization#30]
In [Exercise 7:Task 4](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-4-test-the-function-locally) - Step 7 ; is not working, the desired document is not downloading. 

I performed Task 2 of same Exercise 7, but didn't get the document downloaded.
- So we can also give steps to pass SAS Token and Storage container URL as shown below;

 **OR**
- For this we can instruct users to create public container in [Exercise 6: Task 1](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-1-create-container-for-storing-pdfs-in-azure-storage)

![Appmod](https://user-images.githubusercontent.com/50323628/61951519-d436dd80-afce-11e9-9732-fb54e96b856d.png)

**Comment by SeeratArora** [comment]
@kylebunting   Can you please check on this

**Comment by SeeratArora** [comment]
We have workshop scheduled this week, can you please take this as top priority . 

Thanks in Advance
Seerat Arora

**Comment by timahenning** [comment]
I will make sure we look at this today.

Tim

**Comment by DawnmarieDesJardins** [comment]
Closing with merge.

**Comment by SeeratArora** [comment]
@DawnmarieDesJardins  Any updates on this? We need this ASAP.

**Comment by timahenning** [comment]
There was an update to the HOL that was merged 6 days ago.  Did that fix your issue?

Tim
