### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by ac2707** [microsoft/MCW-App-modernization#32]
Errors - Contoso.FunctionApp

PolicyDocsFunction.cs - no steps in the HOL for TODO 3 and TODO 4 
so this file has errors

Please advise. Urgent.

Thanks

**Comment by timahenning** [comment]
Thank you for letting us know.  We will investigate.

Tim

**Comment by ac2707** [comment]
This can be ignored - the values are added at a later stage.
Closing the issue. 

Thanks.
