### ISSUE TITLE
Need update for below steps

### ISSUE THREAD

**Issue by himanshu311996** [microsoft/MCW-App-modernization#35]
1. In exercise 3 , in lab guide it's mentioned that we have to use  user email for key vault access policies but it was not working so i had to use application id to create access policy.
2. In exercise 9 task 3 , option for profile section is changed
![issues](https://user-images.githubusercontent.com/17895399/65857060-b3995400-e380-11e9-915c-3e3abf581116.png)
![issues2](https://user-images.githubusercontent.com/17895399/65857067-b8f69e80-e380-11e9-9af7-db1ee14020ba.png)

**Comment by kylebunting** [comment]
@himanshu311996, I am not having any issues with using my email address to assign a Key Vault access policy in Exercise 3. My assumption would be that this might be a permissions issue in your subscription.

For the profile access changes in the API Management Developer Portal, I'll get those screenshots and steps updated when I do a test-fix later this month.
