### ISSUE TITLE
Exercise 6, Task 1: Blobs is now Containers

### ISSUE THREAD

**Issue by snpdev** [microsoft/MCW-App-modernization#38]
A minor point perhaps, but in Azure Portal, the Blobs service is now labeled "Containers".

![image](https://user-images.githubusercontent.com/1825479/66857495-6529af00-ef55-11e9-964b-f688a95a41ce.png)

As opposed to the following image in Exercise 6, Task 1:

![image](https://user-images.githubusercontent.com/1825479/66857599-a02be280-ef55-11e9-8e23-21cdde60a709.png)

**Comment by timahenning** [comment]
Thank you for bringing this to our attention Mike.  We have a lab update scheduled for later this month and we will evaluate this suggestion.

Tim

**Comment by kylebunting** [comment]
Fixed is October 2019 test-fix.
