### ISSUE TITLE
Image does not pass color contrast test 

### ISSUE THREAD

**Issue by emilysaeli** [Microsoft/MCW-App-modernization#4]
Image does not pass color contrast test. See test results copied below:

https://github.com/Microsoft/MCW-App-modernization/raw/master/WDS/images/Whiteboarddesignsessionstudentguide-Appmodernizationimages/media/image2.png

Foreground:#FFFFFF
Background:#5B9BD5

The contrast ratio is: just below 3.0:1

Text failed at Level AA
Text failed at Level AAA
Large text failed at Level AA
Large text failed at Level AAA

**Comment by DawnmarieDesJardins** [comment]
Colors resolved and replaced
