### ISSUE TITLE
Azure Bastion Service

### ISSUE THREAD

**Issue by mehmetkut** [microsoft/MCW-App-modernization#43]
Azure Bastion Service can be a nice addition to this workshop.  As you know Port 3389 blocked by default on most of the corporate networks.

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  

We will review your issue soon.

Tim

**Comment by kylebunting** [comment]
Marking this as an enhancement, and we will take it into consideration during the next update cycle.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #81
