### ISSUE TITLE
Access Denied when retrieving policy documents

### ISSUE THREAD

**Issue by bspann** [microsoft/MCW-App-modernization#44]
At the end of Exercise 8 - Task 4 it states "navigate to the Web app URL, and verify you still see data when you select one of the tabs."  The information shows up on the tabs correctly.  When you click on the details of a policyholder and the link to the pdf, you get the following message: 
{ "statusCode": 401, "message": "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API." }

The issue is with AngularJS file located wwwroot/js/app/PolicyHolderController.js.  On line 31 the code looks to be setting all get requests with the API Management Subscription key in the header.  That is not happening.  Using the browser's developer tools, I see the request and the Ocp-Apim-Subscription-Key is missing.  Using fiddler, I confirmed that adding the key-value to the header does work as expected.  

Need to update the code to send the Subscription key so that the website functions as expected.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge #45
