### ISSUE TITLE
Two exercises have same number

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-App-modernization#50]
Hi,

In Step-by-Step lab guide, I see two exercises have the same number.

Exercise 8: Add Cognitive Search for policy documents
   *  Task 1: Add Azure Cognitive Search to Storage account
   *  Task 2: Review search results

Exercise 8: Import and publish APIs into APIM
  *   Task 1: Import API App
  *   Task 2: Import Function App
  *   Task 3: Open Developer Portal and retrieve you API key
  *   Task 4: Update Web App to use API Management Endpoints

Thanks,
Amit Kumar

**Comment by DawnmarieDesJardins** [comment]
@akn9050 
Thanks for the extra set of eyes Amit!  I've corrected the document.
Closing the issue as complete
