### ISSUE TITLE
Exercise 1 Task 1 - Script has 'N' where not allowed

### ISSUE THREAD

**Issue by brharr** [microsoft/MCW-App-modernization#51]
In front of every single string value within the SQL script to prepare the database for Assessment and Migration, there is a capital N. When copying and pasting, this will cause all kinds of errors and is not easy to recognize if this is your first time running through the Lab.

Please remove each one from the Guide. 

Thanks,
Brian

**Comment by kylebunting** [comment]
@brharr, thanks for reporting the issue. The `N` in front of each string in the SQL scripts is intentional and indicates to SQL Server the string is in Unicode. This should not cause any problems in executing the scripts, as it is standard practice in many SQL queries.
