### ISSUE TITLE
Minor Content Update required in the Lab Guide

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-App-modernization#52]
[Exercise 1: Task 1:](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-1-configure-the-contosoinsurance-database-on-the-sqlserver2008-vm) Step 13: The Screenshot needs to be changed, it should one as shown below:

![image](https://user-images.githubusercontent.com/50323628/80582663-ba7a6900-8a2c-11ea-88ad-adc31ca3bf3f.png)

[Exercise 1: Task 5:](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-5-migrate-the-database-using-the-azure-database-migration-service) Step 5: Step 5. On the Migration Wizard **Select source** blade, before saving check **TLS 1.2 security protocol** and then only we can select **Save**.

![image](https://user-images.githubusercontent.com/50323628/80603663-58caf680-8a4e-11ea-98d2-14714972b64b.png)

[Exercise 1: Task 5:](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-5-migrate-the-database-using-the-azure-database-migration-service) Step 13: Validation option: **Not present now in the portal.**

![image](https://user-images.githubusercontent.com/50323628/80603939-ad6e7180-8a4e-11ea-8b9e-82017422369b.png)

**Comment by kylebunting** [comment]
Issue fixed in pull request #54.
