### ISSUE TITLE
Exercise 7: Task 8: Path of the Policy Document doesn't point towards Function App

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-App-modernization#53]
Hi @DawnmarieDesJardins ,
Can you please look into this  and give updates as we have a workshop scheduled soon.

[Exercise 6:Task 2:](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-2-create-a-sas-token) We cannot generate a SAS Token by directly navigating to **storage account> shared access signature>Generate SAS Token** as the Generate SAS Token is greyed out and gives message on the top as shown in the image below:

![image](https://user-images.githubusercontent.com/50323628/81123800-94cff100-8f51-11ea-8632-96d523f5e35e.png)

So now for creating a SAS Token we need to go to **Allowed resource type** and check **Service,** **Container** and **Object**. Then we will be able to generate the SAS Token.

![image](https://user-images.githubusercontent.com/50323628/81123677-4de1fb80-8f51-11ea-877d-ff114890508b.png)

[Exercise 7:Task 6:](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-6-enable-application-insights-on-the-function-app) Step 2: To enable application insights for the function app in azure portal we need to follow the following pattern:

![image](https://user-images.githubusercontent.com/50323628/81124320-c1383d00-8f52-11ea-9116-0358537aa344.png)

[Exercise 7: Task 8:](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-8-test-document-retrieval-from-web-app) Step 5: Path of the Policy Document doesn't point towards Function App as shown below-

![image](https://user-images.githubusercontent.com/50323628/81123396-9d73f780-8f50-11ea-81e9-df6d6dee943d.png)

**Comment by DawnmarieDesJardins** [comment]
@SeeratArora 
Hello!  As you can see above, Tim and Kyle are working on the issue.  If you could please let us know when the workshop is scheduled, that will help us out.  Dawnmarie

**Comment by IT-flavoured** [comment]
Hi,
Regarding **Exercise 7 Task 8**, if it helps somehow, here is the Application Insights drill down of the issue:
![obraz](https://user-images.githubusercontent.com/47644685/81337201-ef309500-90aa-11ea-8029-2bdcd376d140.png)

And APIM test request that is OK:
![obraz](https://user-images.githubusercontent.com/47644685/81337358-27d06e80-90ab-11ea-8756-f39f3b908ce3.png)

Also, in **Exercise 6 Task 2**, going by minimum privilege rule, Blob / Object / Read permissions seems to be enough for this SAS token :)

Keep it up guys! Great work!

Best regards!

**Comment by SeeratArora** [comment]
Hi,

Can you please take a look into this also:
[Exercise 1:Task 5:](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-5-migrate-the-database-using-the-azure-database-migration-service) Step 17: There is no ellipsis button on the toolbar. Else we have a button to download report but it is greyed out. Not sure about why it is like this.

![image](https://user-images.githubusercontent.com/50323628/81414567-ccfb4d80-9164-11ea-8fe7-219eed343ad3.png)

**Comment by timahenning** [comment]
@SeeratArora When is your workshop?

Tim

**Comment by SeeratArora** [comment]
@timahenning  It's on coming Tuesday i.e. 12th May,2020.

**Comment by kylebunting** [comment]
Issue fixed in pull request #54.
