### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-App-modernization#55]

**Comment by codingbandit** [comment]
- go step by step through the lab, add necessary clarifications, and update outdated screenshots
- update projects to the latest .NET Core versions
- include cognitive search into the web application to search for policies (bring it full circle, it is only being setup in the lab and not used)
- add Azure Bastion for RDP access to the VMs
- highlight private endpoints for SQL Database in WDS and HOL (use case: database not exposed to public internet)
- investigate updating to the newest developer portal for API management

**Comment by waltermyersiii** [comment]
Also note that NSGs don't work on private endpoints currently.

**Comment by DawnmarieDesJardins** [comment]
Closing update issue.  Update was changed to a test/fix,
