### ISSUE TITLE
Exercise 5: Task 1: Instruction should be updated

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-App-modernization#56]
[Exercise 5: Task 1:](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-1-add-api-app-url-to-web-app-application-settings) Step 6: The instruction highlighted in the image below needs to be changed.

![image](https://user-images.githubusercontent.com/50323628/85008436-9e688d80-b17a-11ea-97ca-3151821fee62.png)

It should be: `<your-api-default-host-name>`: Replace with the default host name of your API app you copied into a text editor previously.

Thanks.

**Comment by kylebunting** [comment]
@SeeratArora, this is fixed by pull request #57. Closing this issue.
