### ISSUE TITLE
Bulk Upload using AzCopy

### ISSUE THREAD

**Issue by arnoldojperozo** [microsoft/MCW-App-modernization#58]
Exercise 6 - Task 3 upload files to Blob Container using AZCopy command line, but steps are incorrect.

AzCopy implementation changed, now implementing new command mode and proposed CLI does not works.

![image](https://user-images.githubusercontent.com/33009934/88468038-43256b80-ce9b-11ea-919c-f5ac8b549b66.png)

**Comment by arnoldojperozo** [comment]
I was able to solve it using the following command:
./azcopy.exe copy "C:\MCW\MCW-App-modernization-master\Hands-on lab\lab-files\policy-documents\*" "<Blob Container Url>?<SAS Token>"

**Comment by kylebunting** [comment]
@arnoldojperozo, I have not been able to reproduce this issue. I'm assuming from the version of AzCopy you are referencing, you are maybe running this locally or manually installed AzCopy on the LabVM? The instructions in the lab have you download AzCopy from https://aka.ms/downloadazcopy, and that version still works with the instructions provided in the lab. I'm going to close this as resolved, given your ability to solve the issue, and I will note to continue checking this, so the commands can be updated as the version of AzCopy is bumped up during the next round of updates.
