### ISSUE TITLE
Cognitive Search

### ISSUE THREAD

**Issue by arnoldojperozo** [microsoft/MCW-App-modernization#59]
Exercise 8 - Task 2 Cognitive Search Indexer fails

**Azure Error**
Indexing was stopped because the free skillset execution quota has been reached. When no cognitive services subscription is attached to a skillset, only 20 documents can be enriched at a time. To index more documents, attach a cognitive services subscription to your skillset. See https://aka.ms/cog-srch-attach for more information.

**Comment by kylebunting** [comment]
@arnoldojperozo, Exercise 8, Task 1, step 6 already instructs users to attach a Cognitive Services account, so this is already specified within the lab. However, I will insert a note at that step to further explain that failure to complete that step will result in indexing limitations.

**Comment by kylebunting** [comment]
Notes added for this in pull request #61. Closing as resolved.
