### ISSUE TITLE
October 2020 Suggested Updates (ON HOLD)

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-App-modernization#62]

**Comment by kylebunting** [comment]
Suggested updates from the Microsoft team were:

**White Board Design Session**

- .NET Apps Whiteboard Design Session Content  


**Hands-on Lab Exercises & Tasks**

Note, the below flow is not the current experience on GitHub, but rather the recommended flow based on the new .NET App demo the .NET stakeholders have already identified as what we’d like to see in the .NET HOL content. 

1. Migration assessment and inventory using Azure Migrate – central hub of tools to discover, assess, and migrate workloads to Azure
    - Start with the current Tailwind Traders web application and a SQL Server database hosted on VMs
    - Use Azure Migrate to scan the existing resources looking for web application/s and database/s to migrate from on-prem/VMs to Azure
    - Identify the tools/services that can automate the migration
2. Migrate the application layer using App Service Migration Assistant tool – service specifically designed to migrate .NET web apps to Azure App Service
    - Download local agent for web app migration assessment and readiness checks
    - Follow the wizard to automate the migration of a Windows hosted (IIS server) ASP.NET web application to Azure App Service
3. Migrate the data layer using Azure Database Migration Service – simplify, guide, and automate SQL databases migration to Azure SQL
    - The target for migration in Azure would be an Azure SQL database
    - Use Database Migration Assistant (DMA) to do a pass on the source data to detect potential compatibility issues and detect partially supported/unsupported features, as well as helping on choosing the right size and appropriate Azure service tier
    - Perform the live migration with zero downtime using Azure Database Migration Service (DMS) 
    - Configure the connection between the web application and the migrated database
4. Setup CI/CD pipeline with GitHub Actions for the web app
    - Connect to source code repository
    - Create service principal and Configure GitHub secret
    - Configure the Action steps to setup the environment and build the web app
    - Commit some change/s to the web app to automatically deploy to App Service

**Comment by DawnmarieDesJardins** [comment]
Content changes sign-off received via email:

From: Miwa Monji 
Sent: Tuesday, October 13, 2020 12:48 PM
Subject: RE: App modernization - Content update confirmation

Yes, the workflow looks good.  Let me know if you need any assistance.

Thank you,

Miwa

From: Gorka Madariaga Nunez 
Sent: Tuesday, October 13, 2020 12:31 PM
Subject: RE: App modernization - Content update confirmation

Looks good to me, it’s the exact same flow we have on the current demo, so if that’ the goal here it’s all good. 

Thanks,
Gorka

**Comment by DawnmarieDesJardins** [comment]
Update on Hold - marking issue as an enhancement until further notice.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #81
