### ISSUE TITLE
Confused with two repositories with the same or similar content

### ISSUE THREAD

**Issue by ddobric** [microsoft/MCW-App-modernization#63]
What is the difference between these two repositories?
https://github.com/microsoft/MCW-App-modernization
https://github.com/microsoft/.NET-Modernization-In-a-Day

To me it looks as they would have the same content.

**Comment by kylebunting** [comment]
@ddobric, I cannot speak to the intent of the other repo, but the https://github.com/microsoft/MCW-App-modernization repo is the "official" Microsoft Cloud Workshop and is being maintained by that team. It does appear the other repo you listed is a copy of this one and the content might be something they are going to use for a single day workshop. 

We are also in the process of making some fairly large updates to this workshop, so changes will be coming in the next month or so.
