### ISSUE TITLE
Run into error at excercise 7 "Create serverless API for Accessing PDFs"

### ISSUE THREAD

**Issue by maxfjacob** [microsoft/MCW-App-modernization#64]
@ task 4: "test the functionality locally" -> In Visual Studio "Debug" -> "Start new instance" the message occurs: "There were build errors. Would you like to continue and run the last successful build?"

I did the changes as described in the task 3 and saved the PolicyDocsFunction.cs file. (see attachment). Any hint why I run into this problem?

[PolicyDocsFunction.txt](https://github.com/microsoft/MCW-App-modernization/files/5386573/PolicyDocsFunction.txt)

**Comment by kylebunting** [comment]
@maxfjacob, I see the issue in your code. It appears you have duplicate function definition lines added. You need to overwrite the existing function declaration with the one specified in task 3.

![image](https://user-images.githubusercontent.com/5960229/98047757-7c566b80-1dfa-11eb-8888-1796be21d081.png)

I've attached the corrected code for you to try.

[PolicyDocsFunction-fix.txt](https://github.com/microsoft/MCW-App-modernization/files/5484424/PolicyDocsFunction-fix.txt)

**Comment by DawnmarieDesJardins** [comment]
@maxfjacob 
Hello.  Please let us know if Kyle's code worked for you so we can close the issue or investigate further.  Thank you.

**Comment by maxfjacob** [comment]
It worked...thx

________________________________
Von: Dawnmarie DesJardins <notifications@github.com>
Gesendet: Thursday, November 12, 2020 5:32:49 PM
An: microsoft/MCW-App-modernization <MCW-App-modernization@noreply.github.com>
Cc: maxfjacob <max.f.jacob@outlook.com>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/MCW-App-modernization] Run into error at excercise 7 "Create serverless API for Accessing PDFs" (#64)


@maxfjacob<https://github.com/maxfjacob>
Hello. Please let us know if Kyle's code worked for you so we can close the issue or investigate further. Thank you.

**Comment by kylebunting** [comment]
Marking as closed, based on submitter's last comment.
