### ISSUE TITLE
Can't find content in MCW folder and No VS2019 in Exercise 4

### ISSUE THREAD

**Issue by wely** [microsoft/MCW-App-modernization#68]
Hi folks, 

I am following the lab till [Exercise 4](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-2-open-starter-solution-with-visual-studio)

I'd like to raise an issues in LabVM: I can't find the content from the MCW folder:
![image](https://user-images.githubusercontent.com/1658657/99222896-6b582200-281e-11eb-8954-10574321149b.png)

**Comment by wely** [comment]
To give some additional context, i then check the VM's Extension and click the "View detailed status":
![image](https://user-images.githubusercontent.com/1658657/99227994-fc32fb80-2826-11eb-8259-bc0ecd071bcb.png)

Here're the details i am getting:
[
    {
        "code": "ComponentStatus/StdOut/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "IE Enhanced Security Configuration (ESC) has been disabled.\r\n"
    },
    {
        "code": "ComponentStatus/StdErr/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "Stop-Process : Cannot find a process with the name \"Explorer\". Verify the \r\nprocess name and call the cmdlet again.\r\nAt C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.9\\Downloads\r\n\\0\\configure-labvm.ps1:6 char:5\r\n+     Stop-Process -Name Explorer -Force\r\n+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (Explorer:String) [Stop-Process] \r\n   , ProcessCommandException\r\n    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell. \r\n   Commands.StopProcessCommand\r\n \r\nInvoke-WebRequest : The request was aborted: Could not create SSL/TLS secure \r\nchannel.\r\nAt C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.9\\Downloads\r\n\\0\\configure-labvm.ps1:14 char:1\r\n+ Invoke-WebRequest 'https://github.com/microsoft/MCW-App-modernization ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt \r\n   pWebRequest) [Invoke-WebRequest], WebException\r\n    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe \r\n   ll.Commands.InvokeWebRequestCommand\r\n \r\nExpand-Archive : The path 'C:\\MCW.zip' either does not exist or is not a valid \r\nfile system path.\r\nAt C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.9\\Downloads\r\n\\0\\configure-labvm.ps1:15 char:1\r\n+ Expand-Archive -LiteralPath 'C:\\MCW.zip' -DestinationPath 'C:\\MCW' -F ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidArgument: (C:\\MCW.zip:String) [Expand-Arc \r\n   hive], InvalidOperationException\r\n    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive\r\n \r\n"
    }
]

**Comment by wely** [comment]
after spending sometime to debug, i propose the this PR to resolve the issue: https://github.com/microsoft/MCW-App-modernization/pull/69

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #69
