### ISSUE TITLE
No VS2019 installed on the VS2019 VM Images

### ISSUE THREAD

**Issue by wely** [microsoft/MCW-App-modernization#70]
There's an issue when provisioning VM with VS2019 (latest) using this:

"imageReference": {
                        "publisher": "microsoftvisualstudio",
                        "offer": "visualstudio2019latest",
                        "sku": "vs-2019-ent-latest-ws2019",
                        "version": "latest"
                    },

For some reason, VS2019 installed installed:
![image](https://user-images.githubusercontent.com/1658657/99356718-922d5b80-28e5-11eb-8d05-4ef5d5083eec.png)

I have submitted a ticket thru Azure Support about this issue. While it will take some time for resolution, the workaround is to use this image:

"storageProfile": {
                    "imageReference": {
                        "publisher": "microsoftvisualstudio",
                        "offer": "visualstudio2019",
                        "sku": "vs-2019-ent-ws2019",
                        "version": "latest"
                    },

I'll submit a PR for this shortly.

**Comment by wely** [comment]
I created a PR to resolve the issue temporary by using another image:
https://github.com/microsoft/MCW-App-modernization/pull/71

![image](https://user-images.githubusercontent.com/1658657/99357166-6bbbf000-28e6-11eb-8739-ff13ac9d4144.png)

**Comment by wely** [comment]
Do this step (in case my PR has not been approved on-time) :)

1) When clicking the "Deploy to Azure" Button in [this step](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20App%20modernization.md#task-3-run-arm-template-to-provision-lab-resources)

2) Hit the "Edit template" in the Custom deployment.
![image](https://user-images.githubusercontent.com/1658657/99358866-19300300-28e9-11eb-8014-9405fd2ac1ee.png)

3) Search for "imageReference" which supposed to be in about Line 113. Replace the publisher and offer to the followings:
                    "imageReference": {
                        "publisher": "microsoftvisualstudio",
                        **"offer": "visualstudio2019",
                        "sku": "vs-2019-ent-ws2019",**
                        "version": "latest"
                    }

**Comment by wely** [comment]
Update! the image issue has been fixed by the Azure backend team:
![image](https://user-images.githubusercontent.com/1658657/99478915-37047300-2990-11eb-873d-a5520d9e277a.png)

So, folks you can ignore my workaround / comment above

**Comment by kylebunting** [comment]
Following up to say the VM image for VS 2019 Community edition appears to have been fixed and is now installing VS 2019 Community correctly.
