### ISSUE TITLE
Azure API Management Developer portal (legacy) is no longer accessible 

### ISSUE THREAD

**Issue by wely** [microsoft/MCW-App-modernization#72]
https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-3-open-developer-portal-and-retrieve-you-api-key

The UI and instruction needs to change to the new developer portal

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #77
