### ISSUE TITLE
Issue while deploying  web application to Azure 

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-App-modernization#74]
[Exercise 5 Task2 Step6](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-2-deploy-web-application-to-azure) 

I am getting this below error after publishing the **Contoso.Web** web application from Visual studio. Please find the attached screenshot for reference. However it worked when I installed the NuGet pacakge **Microsoft.NET.Sdk.Razor**.

![appmodissue1](https://user-images.githubusercontent.com/52440474/100989383-d2900900-3576-11eb-88df-f3bd3df0847c.png)

We have workshop scheduled this week. Can you please try to fix this asap.

**Comment by tejaswini972** [comment]
Resolved.

**Comment by ekuipers** [comment]
This error is due to Visual Studio not able to find the dotnet package for Dotnet Core 2.2 after an upgrade to .NET version 5.

Solution: Add a Windows environment variable to your system settings:
DOTNET_HOST_PATH=%ProgramFiles%\dotnet\dotnet.exe
