### ISSUE TITLE
Instructions and Screenshots Update

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-App-modernization#76]
[Exercise1 Task5](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-5-migrate-the-database-using-the-azure-database-migration-service)

Step5,7,9,11 and 13 : Screenshot needs to be updated.

![migration1](https://user-images.githubusercontent.com/52440474/102998215-c3d0bc80-454c-11eb-822d-aca2b6d04cc2.png)

![migration2](https://user-images.githubusercontent.com/52440474/102998216-c501e980-454c-11eb-80ad-b2f713891e38.png)

![migration3](https://user-images.githubusercontent.com/52440474/102998245-d0edab80-454c-11eb-9f77-f539a8c92be9.png)

![migration4](https://user-images.githubusercontent.com/52440474/102998272-dcd96d80-454c-11eb-86f2-299dd58eee87.png)

![migration5](https://user-images.githubusercontent.com/52440474/102998303-e9f65c80-454c-11eb-8f94-d6e42e37ea39.png)

[Exercise2 Task1](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-1-configure-sql-data-discovery-and-classification)

As portal got updated, I am not able to find **Advance Data Security** under settings. However I was able to perform Task1 by selecting **Data Discovery & Classification**.

![issue1](https://user-images.githubusercontent.com/52440474/102997764-d3033a80-454b-11eb-8234-1f62ccd9efe8.png)

[Exercise2 Task2](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-2-review-advanced-data-security-vulnerability-assessment)

Not able to find **Vulnerability Assessment** tile.

[Exercise6 Task1 Step3](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-1-create-container-for-storing-pdfs-in-azure-storage) : Screenshot update.

![storageaccount](https://user-images.githubusercontent.com/52440474/102999190-997ffe80-454e-11eb-803f-3ad958c5130e.png)

Step 5:

Instruction and Screenshot needs to be updated(To copy the Key1 key, first I had to click **Show Keys** ).

![issue2](https://user-images.githubusercontent.com/52440474/102999512-21660880-454f-11eb-8455-ba7a2fbfcd44.png)

[Exrecise9 Task3](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-3-open-developer-portal-and-retrieve-you-api-key)

Not able to select **Developer portal (legacy)** from the Overview blade of your API Management service in the Azure portal.

![issue3](https://user-images.githubusercontent.com/52440474/102999722-976a6f80-454f-11eb-8d2a-5724cfc84a66.png)

**Comment by kylebunting** [comment]
@tejaswini972, we are about to kick off a major update cycle for this lab and will be making the fixes you suggested above as part of that. We should have the new version of the lab released by the middle of February 2021.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #81
