### ISSUE TITLE
Mobile App Deprecated?

### ISSUE THREAD

**Issue by snpdev** [microsoft/MCW-App-modernization#79]
In the App modernization Whiteboard Design Session documents there are references to the Mobile App, Azure resource. For instance, the following question in [WDS trainer guide - App modernization.md](https://github.com/microsoft/MCW-App-modernization/blob/master/Whiteboard%20design%20session/WDS%20trainer%20guide%20-%20App%20modernization.md):

> 3.	What Azure service would host the services supporting the mobile app backend? Would you suggest a Mobile App or an API App? Why?

If I'm not mistaken, the Mobile App resource was [deprecated in November 2019](https://azure.microsoft.com/en-us/updates/removing-easy-tables-and-easy-apis-from-azure-app-service/) and going forward one would use an App Service API App, Azure Function or other service, e.g. AKS, for their mobile back-end.

There is no reference to the Mobile App resource in the hands-on-lab.

**Comment by kylebunting** [comment]
@snpdev, thanks for the input. We are in the process of updating this workshop and this will be addressed. We are making some big changes to this one, and the mobile app components are being completely removed.
