### ISSUE TITLE
Issue in exercise 5, Task 2, step 14: No data available under "Manage Policy Holders"

### ISSUE THREAD

**Issue by Eddevinc** [microsoft/MCW-App-modernization#80]
Issue in exercise 5, Task 2, step 14: No data available under "Manage Policy Holders".

I have performed the lab exactly as mentioned in the lab guide yet facing this issue.

![image](https://user-images.githubusercontent.com/32365275/107712724-eb900580-6cef-11eb-9a6c-37d21108259b.png)

**Comment by himanshuahlawat31** [comment]
@timahenning can you please suggest something on this we have tried the lab twice and yet data is not coming up

**Comment by himanshuahlawat31** [comment]
Hi we were able to past through the step but we are facing issue with azure function tools core version 
![image](https://user-images.githubusercontent.com/57964598/107836812-688caf00-6dc4-11eb-91da-386fd8230062.png)
can you please suggest something on this we are using latest sdk version of .net as well

**Comment by SeeratArora** [comment]
Hi @kylebunting/ @timahenning 
Please let us know if we have updates on this.

**Comment by timahenning** [comment]
Hi @SeeratArora,

We are about to release a major rewrite of this lab in the next couple of weeks.  In the meantime, we will try to reproduce your error.

**Comment by mrfx2020** [comment]
Hi @timahenning we have an Azure Immersion Workshop scheduled for the 3rd of March, could you give us an estimated date for this lab to be working?

**Comment by timahenning** [comment]
Hi @mrfx2020 The updates are scheduled to be released on March 3rd.  You can review the upcoming changes in the 2021Updates branch.

**Comment by timahenning** [comment]
Hi @mrfx2020, Did you test the 2021Updates branch? It is going to be released in the next couple of weeks.

**Comment by mrfx2020** [comment]
Hi @timahenning if I want to test the 2021Updates branch, do I have to deploy the lab on my own environment? I'm using the CloudLabs environment so I'm not sure how I can test the 2021Updates.

**Comment by kylebunting** [comment]
@mrfx2020, yes, that would be the case. The CloudLabs environment is not yet using the latest branch, as that is still going through the review and QC process.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #81
