### ISSUE TITLE
There is no Master branch for the repository now

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-App-modernization#85]
There is no Master branch for the repository now, branch name used in variables in Arm template and scripts need to be changed to main

**Comment by timahenning** [comment]
The **master** branch was changed to **main** for MS compliance purposes yesterday.  Everything should still function.  We will update the scripts.

**Comment by timahenning** [comment]
@akn9050 We will be working on this today.

**Comment by DawnmarieDesJardins** [comment]
@akn9050 
Hi Amit.  First PR merged to update master to main changes.  Chris is retesting now so more PRs may follow.  We'll keep this issue open until everything is complete and close it when your team can update your labs.

**Comment by givenscj** [comment]
We are working on this today (4/16/2021).

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #88
