### ISSUE TITLE
Error while running the mobile application

### ISSUE THREAD

**Issue by ShivaniThadiyan** [Microsoft/MCW-App-modernization#9]
Ex-11 – Task:2: We setup Xamarin environment, we’re installing Android SDK, when we try to build the solution we get the following  ( https://dcstgac.blob.core.windows.net/apperror/error.png )error. The default installation of Xamarin did not come with emulator, we added it manually.

**Comment by kylebunting** [comment]
Reassigning to @jstulo

**Comment by jstulo** [comment]
The emulator is included in the Mobile development with .NET workload for Visual Studio 2017.
The workloads required are specified in Before the HOL - Task 4 step 3.
