### ISSUE TITLE
Security alert - trim-newlines

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-App-modernization#91]
Opening issue for review - security alert rated high severity.  Please review/advise.

 ![image](https://user-images.githubusercontent.com/39317565/121555452-e013c900-c9c7-11eb-9e7e-b86b46d95886.png)

**Comment by kylebunting** [comment]
@DawnmarieDesJardins, we can safely ignore this error until the next test-fix or update of this workshop. This library is referenced in the starter solution, but we aren't running this site for anything other than the workshop, so it is not critical that we fix it immediately.
