### ISSUE TITLE
Issue with Azure Migrate

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-App-modernization#94]
[Exercise 2 Task 2 Step 8](https://github.com/microsoft/MCW-App-modernization/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-2-migrate-the-web-application-to-azure-app-service) : After the successful migration of web application to Azure App Service, the number of discovered web servers, assessed websites and migrated websites values are not changed from 0 to 1. The discovered server is visible under appliance page and the website is also working. Please find the attached below screenshots below for reference.

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/52440474/127449911-dd7777cd-f320-4ac6-8a2a-c420c2cb503b.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/52440474/127449917-376357df-1700-439e-9e7d-4275708bf2d7.png)

We have workshops scheduled for tomorrow. Can you please prioritize this and work on it??

**Comment by daronyondem** [comment]
Hi @tejaswini972 ,

Thanks for reaching out. Sometimes it takes a while for the uploaded report to show up on the portal. It might take up to 10 minutes for the results to show up. If not, ensure you have picked the right Azure Migrate project during Exercise 2 Task 2 Step 5. 

For your workshop tomorrow, considering the short time you have I would like to remind you that the numbers in the discovery do not affect the Lab itself. If the migration is completed successfully learners can continue the lab with no issues. 

I hope this helps. 

Thanks

**Comment by tejaswini972** [comment]
Hi @daronyondem 

Thanks for the information!!

Please be informed that I created a single Migrate project and used it for performing migration. Even after 5-6 hours the numbers in the discovery was not updated.

**Comment by DawnmarieDesJardins** [comment]
@tejaswini972 
Hello!  I hope this helps for your workshop tomorrow.  For future reference, we advise 5-10 business days for issue review and resolution.  Please test early so we can provide you with the best support.

**Comment by daronyondem** [comment]
Hi @tejaswini972

Just did a test run in a freshly deployed lab environment. I saw the results in a couple of minutes. 

![image](https://user-images.githubusercontent.com/2984187/128137827-13bdfba6-6986-4b77-aa56-47bea829930b.png)

Unfortunately, I'm not able to reproduce your issue. Can you give the lab another try and make sure you are not skipping a step. 

Let us know your findings.

Thanks
