### ISSUE TITLE
Issue in Ex4 Task1

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-App-modernization#98]
[Exercise 4 Task 1 Step 13](https://github.com/microsoft/MCW-App-modernization/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-1-moving-the-codebase-to-a-github-repo): As per the instruction, a browser pop-up should appear with the GitHub login page to login to the GitHub, but it asked to enter the credentials in Powershell. When I entered the username and password, the push operation failed with the below error.

**remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.**

Please find the attached screenshot below for reference.

![appmodissue](https://user-images.githubusercontent.com/52440474/131585385-c50d788c-e26d-406a-bc6d-4a2b1bb0e040.png)

**Comment by timahenning** [comment]
Hi @tejaswini972,

I followed the instructions last night and it worked.  You can use a personal token.  You will have to generate one.

![image](https://user-images.githubusercontent.com/48766586/132789162-5b9c02bc-bc0b-4e35-b4ee-f0b64d1e96ec.png)


Tim

**Comment by tejaswini972** [comment]
Hi @timahenning,

Yes, we can generate personal access token and use it to push the code. 

Can we add instructions regarding this in lab guide??

Thanks,
Tejaswini.

**Comment by timahenning** [comment]
The current lab instructions work.  The personal access token is optional.
