### ISSUE TITLE
Enhancement required in Webapp Source code

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-App-modernization#99]
[Exercise 4 Task 3 Step 8](https://github.com/microsoft/MCW-App-modernization/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-3-setting-up-cicd-with-github-actions): While **Setting up CI/CD with GitHub Actions**, after pushing the source code to GitHub then when we try to create connection between the App Service deployment slot and the GitHub repository, the workflow will fail due to .NET Core version mismatch.

Can source code be configured based on **.Net 3.1** so while running the lab there will be no requirement of changing the .Net core version manually in Step 13 and it will enhance user experience??

**Comment by timahenning** [comment]
We narrowed the issue down to an update to the default version of IIS deployed in the ARM template.  We are going to update the ARM template and update the instructions to use a new explicit version.

**Comment by timahenning** [comment]
Additional changes are being made to the lab to make sure the lab will work for a longer period of time.  We are upgrading the solution to .NET Core 3.1 LTS.  This is taking more time than expected.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of RP #102
